--liquibase formatted sql

--changeset satdarov:008-expand-keywords
INSERT INTO keyword_weights (category_name, keyword, weight, created_at) VALUES
-- Проблемы с авторизацией (новые слова)
('Проблемы с авторизацией', 'авторизация', 10.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'авторизоваться', 9.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'аутентификация', 9.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'аккаунт', 8.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'учетная', 8.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'заблокирован', 8.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'заблокировали', 8.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'разблокировать', 8.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'токен', 7.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'сессия', 7.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'двухфакторная', 7.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'смс', 6.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'подтверждение', 6.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'регистрация', 6.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'зарегистрироваться', 6.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'забыл', 7.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'сбросить', 7.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'восстановить', 7.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'кабинет', 6.0, CURRENT_TIMESTAMP),
('Проблемы с авторизацией', 'профиль', 5.0, CURRENT_TIMESTAMP),

-- Технические проблемы (новые слова)
('Технические проблемы', 'вылетает', 9.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'зависает', 9.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'зависло', 9.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'тормозит', 8.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'тормоза', 8.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'медленно', 7.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'сломалось', 8.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'глючит', 9.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'глюк', 9.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'крашится', 9.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'краш', 8.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'приложение', 7.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'программа', 7.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'сайт', 7.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'страница', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'загружается', 7.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'загрузка', 7.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'обновление', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'установить', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'телефон', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'андроид', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'айфон', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'ios', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'android', 6.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'exception', 8.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'fatal', 8.0, CURRENT_TIMESTAMP),
('Технические проблемы', 'технический', 7.0, CURRENT_TIMESTAMP),

-- Проблемы с оплатой (новые слова)
('Проблемы с оплатой', 'платить', 10.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'оплатить', 12.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'транзакция', 10.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'перевод', 9.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'списание', 10.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'списали', 10.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'возврат', 9.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'вернуть', 9.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'refund', 9.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'отклонена', 9.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'отклонили', 9.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'отказ', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'банк', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'банком', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'visa', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'mastercard', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'баланс', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'недостаточно', 8.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'подписка', 7.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'тариф', 7.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'сумма', 7.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'покупка', 7.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'заказ', 7.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'чек', 6.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'квитанция', 6.0, CURRENT_TIMESTAMP),
('Проблемы с оплатой', 'реквизиты', 7.0, CURRENT_TIMESTAMP);

--rollback DELETE FROM keyword_weights WHERE created_at >= NOW() - INTERVAL '1 minute';