ALTER TABLE tickets ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMP;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE tickets RENAME COLUMN status TO ticket_status;