input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![timestamp] {
    mutate {
      add_field => { "timestamp" => "%{@timestamp}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "issueinsight-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
